### ISSUE TITLE
How to make hemisphere?

### ISSUE THREAD

**Issue by getarobo** [d-ronnqvist/DRMeshGeometry#6]
Hi how would I make hemisphere with this?

I am trying to create hemisphere so I can texture map my fisheye video.

I am having trouble creating triangle index for hemisphere.

Thankyou!!!!

**Comment by d-ronnqvist** [comment]
You can create a sphere geometry from 0 to π for both `thetaRange` and `psiRange`, with a constant radius. Something like this:

```
DRSphereMeshGeometryBuilder *sphereBuilder = [[DRSphereMeshGeometryBuilder alloc] init];
sphereBuilder.thetaRange = DRMeshRangeMake(0, M_PI);
sphereBuilder.psiRange   = DRMeshRangeMake(0, M_PI);

CGFloat radius = 10.0; // whatever your radius is
SCNGeometry *hemisphere = [sphereBuilder geometryWithSphereFunction:^CGFloat(CGFloat theta, CGFloat psi) {
    return radius;
}];
```
